#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Carp-Assert-More
Version  : 1.16
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/Carp-Assert-More-1.16.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/Carp-Assert-More-1.16.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libcarp-assert-more-perl/libcarp-assert-more-perl_1.16-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Carp-Assert-More-man
BuildRequires : perl(Carp::Assert)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)

%description
# Carp::Assert::More
[![Build Status](https://travis-ci.org/petdance/carp-assert-more.svg?branch=dev)](https://travis-ci.org/petdance/carp-assert-more)

%package man
Summary: man components for the perl-Carp-Assert-More package.
Group: Default

%description man
man components for the perl-Carp-Assert-More package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Carp-Assert-More-1.16
mkdir -p %{_topdir}/BUILD/Carp-Assert-More-1.16/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Carp-Assert-More-1.16/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Carp/Assert/More.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Carp::Assert::More.3
